-- SQLite schema adapted from MySQL

CREATE TABLE IF NOT EXISTS socios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  documento TEXT NOT NULL UNIQUE,
  email TEXT,
  estado TEXT NOT NULL DEFAULT 'ACTIVO',
  fecha_alta DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS libros (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  autor TEXT,
  categoria TEXT,
  isbn TEXT UNIQUE,
  precio REAL,
  stock INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ejemplares (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  libro_id INTEGER NOT NULL,
  codigo_barra TEXT NOT NULL UNIQUE,
  estado TEXT NOT NULL DEFAULT 'DISPONIBLE',
  ubicacion TEXT,
  FOREIGN KEY(libro_id) REFERENCES libros(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prestamos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  socio_id INTEGER NOT NULL,
  ejemplar_id INTEGER NOT NULL,
  fecha_prestamo DATETIME NOT NULL,
  fecha_vencimiento DATETIME NOT NULL,
  fecha_devolucion DATETIME NULL,
  estado TEXT NOT NULL,
  FOREIGN KEY(socio_id) REFERENCES socios(id),
  FOREIGN KEY(ejemplar_id) REFERENCES ejemplares(id)
);

CREATE TABLE IF NOT EXISTS reservas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  socio_id INTEGER NOT NULL,
  libro_id INTEGER NOT NULL,
  fecha DATETIME NOT NULL,
  estado TEXT NOT NULL,
  FOREIGN KEY(socio_id) REFERENCES socios(id),
  FOREIGN KEY(libro_id) REFERENCES libros(id)
);

CREATE TABLE IF NOT EXISTS multas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  socio_id INTEGER NOT NULL,
  prestamo_id INTEGER NOT NULL,
  monto REAL NOT NULL,
  fecha DATETIME NOT NULL,
  pagada INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(socio_id) REFERENCES socios(id),
  FOREIGN KEY(prestamo_id) REFERENCES prestamos(id)
);

CREATE TABLE IF NOT EXISTS auditoria (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  usuario_id INTEGER NULL,
  accion TEXT NOT NULL,
  entidad TEXT NOT NULL,
  entidad_id INTEGER NULL,
  fecha DATETIME NOT NULL,
  detalle TEXT
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Usuario TEXT NOT NULL UNIQUE,
  Clave TEXT NOT NULL,
  EsAdmin INTEGER NOT NULL DEFAULT 0
);
